spring:
  application:
    name: order
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:60387;databaseName=interview;encrypt=true;trustServerCertificate=true
    username: sa
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR